travis: don't ask for freetype on osx, should fix build
freetype is already installed on osx and the version difference started
causing errors, while we don't care about the version:

Error: freetype 2.10.1 is already installed

To upgrade to 2.10.2, run `brew upgrade freetype`.