Fix compilation under g++ 11.5
The g++ 11.5 can't compile CREImporter.cpp:

```
88:/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:34: error: ‘char* __builtin_strncpy(char*, const
char*, long unsigned int)’ offset [0, 7] is out of the bounds [0, 0] [-Werror=array-bounds]
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘GemRB::FixedSizeString<LEN, CMP>& GemRB::FixedSizeString<LEN, CMP>::operator=(const STR&) [
with STR = char [5]; typename std::enable_if<((((! std::is_enum<T>::value) && (! std::is_fundamental<STR>::
value)) && (! std::is_pointer<T>::value)) || std::is_same<STR, const char (&)[1]>::value), int>::type
<anonymous> = 0; long unsigned int LEN = 8; int (* CMP)(const char*, const char*, size_t) = strncasecmp]’ at
/tmp/opencode/gemrb-master/gemrb/core/Strings/CString.h:122:10,
    inlined from ‘virtual GemRB::Actor* GemRB::CREImporter::GetActor(unsigned char)’ at /tmp/opencode/gemrb-
master/gemrb/plugins/CREImporter/CREImporter.cpp:883:25:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:34: error: ‘char* __builtin_strncpy(char*, const
char*, long unsigned int)’ offset [0, 7] is out of the bounds [0, 0] [-Werror=array-bounds]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Trigger line is CREImporter.cpp:883: `act->SmallPortrait = "NONE";` ("NONE" = char[5], target ResRef=FixedSizeString<8>).

The new `CopyFrom` helper first measures the actual length of the source range, then copies only `min(sourceLength, LEN)`
characters into the fixed buffer and fills the rest of the buffer with zeros.
Because the copy never asks to read more bytes than the source actually contains, GCC's bounds check passes.
The buffer is still always zero-padded and NUL-terminated, so behavior is unchanged.