ResRef: added copy constructor
error: definition of implicit copy constructor for 'ResRef' is deprecated
 because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]