Window::Close: make idempotent for the destruction case
fixes these errors on esc-ing out of the inventory:
[Python/ERROR]: RuntimeError: Cannot construct object with null ref.
[Python/ERROR]: TypeError: InventoryClosed() missing 1 required positional argument: 'win'

WindowManager::DispatchEvent is calling Close again in this case, but there's
nothing more to be done